### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by damien-carcel** [akeneo/Dockerfiles#160]
- Explain that the PIM must first be cloned, then a compose file place in it
- Make clear that `--ignore-platform-reqs` is only for PHP 7.x **AND** MongoDB
- Add a "Getting started" section to the documentation
    - Add links to relevant Docker documentation (installation, docker-compose…)
    - Explain each part of the compose files (why the networks, the mapping of the ports and the volumes…)
- Differences between FPM + nginx and Apache images should be better documented
    - maybe with subsections for each, main file containing only an introduction and the link to different subsections
- Describe the scripts (with a link to it) that are added in the Akeneo images
- ~~Add an introduction to PHPStorm debugger configuration (add links to relevant PHPStorm documentation)~~ This is a big work. It will be done in another issue.

**Comment by jmleroux** [comment]
* `--ignore-platform-reqs` should not be by default, only in an example with php7.0 

But for the rest, it's a big +1 !

**Comment by jmleroux** [comment]
and when these images are stable, i also vote for them to be in the PIM repo

**Comment by damien-carcel** [comment]
@jmleroux I added your comment to my todo list and will work on it this weekend.

For the question of added it to the PIM repo, it needs to be discussed with the Akeneo core team, but I'd love to have a `docker-compose.yml.dist` in it 😃.
