### ISSUE TITLE
Add this repo on Packagist

### ISSUE THREAD

**Issue by jmleroux** [akeneo/Dockerfiles#165]
One idea if the docker-compose files are not integrated in the PIM: could we not make this repo available via composer to be able to add on dev requirements?
A simple post-install script could move the docker-compose files at the right in the PIM and voilà: we could use `docker-compose`.

**Comment by damien-carcel** [comment]
Maybe not in the require-dev, as only the compose file is really needed, but it could be in the suggestions, as you can add a message to it.
