### ISSUE TITLE
Check CI possibilities

### ISSUE THREAD

**Issue by damien-carcel** [akeneo/Dockerfiles#24]
Right now, there is no check prior to PR than building and running the docker images locally.
A dockerfile checkstyle should also be added.

Check what exists in term of continuous integration.

**Comment by anaelChardan** [comment]
You can take a look at this repo : https://github.com/docker-library/php they have a travis running :)

**Comment by damien-carcel** [comment]
Yep, I saw that. In fact, they use the same kind of CI on all "official" images: building them, in order, on travis, them run some tests on them.
Kind of the idea we came with IRL, and I don't really see another way.

I will work on that during Christmas holidays.
