### ISSUE TITLE
Use CI to build the images

### ISSUE THREAD

**Issue by damien-carcel** [akeneo/Dockerfiles#282]
## Description

Docker Hub is currently used to build the images. However, they are already build by the CI (Travis-CI as of now) to run the tests.
Once the tests are green and PR can be merged, the CI should be responsible to push the images right after the merge.

## Prepare

- [x] Put every image tags on master branch, in sub-directories => Issue #284

## First phase - Testing

This needs to be first tested with a test Dockerfile and repository:
- [x] to see how it can be done,
- [x] to see if Travis-CI can be used or if we need to switch to another tool.

## Second phase - Implementing

If first phase is conclusive:
- [x] Deactivate Docker Hub builds
- [x] Use the CI to push the images on Docker Hub

**Comment by stefandoorn** [comment]
@damien-carcel First phase also done here, isn't it?

**Comment by damien-carcel** [comment]
Hey @stefandoorn.

No, it is not done yet. We know TravisCI can build the images. What we need to test is to push the builded images to Docker Hub (instead of building them with Travis to run the tests, then build them again with Docker Hub once the PR is merged).

What's more, we recently switch to Circle CI for Akeneo PIM. It could be interesting to test is as well, as it is more advanced than Travis regarding Docker usage.
