### ISSUE TITLE
Add PHP 7.2

### ISSUE THREAD

**Issue by damien-carcel** [akeneo/Dockerfiles#283]
| Q                      | A
| ---------------------- | -----
| Bug report?            | no
| Feature request?       | yes
| BC Break report?       | no
| RFC?                   | no
| Affected image and tag | -

PHP 7.2 is available in Sury repositories. This should become the new `latest`, along with `php-7.2` branch corresponding Docker Hub tags. A new documentation section should be added too, explaining the update process.

### PRs to be done

- [x] Change the image organization
    - each version is now in its own subfolder, only the last version contains a README for the Docker Hub
    - the CI scripts need to be updated accordingly (this should only affect the image builder)
    - update the automated builds on Docker Hub
- [x] Add the PHP 7.2 Dockerfiles
    - add them for `akeneo/php`, `akeneo/fpm` ~~and `akeneo/apache-php`~~ (no more apache-php images)
    - add the documentation about adding a new image and its tests
    - run the tests on these new Dockerfiles
    - update the automated builds on Docker Hub

**Comment by jmleroux** [comment]
FYI, I recently add problem with php 7.2 and mcrypt when upgrading my own Dockerfiles.

http://php.net/manual/fr/migration71.deprecated.php

:wink:

**Comment by damien-carcel** [comment]
Yep, I know about it. I will see how it behaves and how the PIM will react.
