### ISSUE TITLE
Simplify PHP_XDEBUG_ENABLED condition

### ISSUE THREAD

**Issue by lars85** [akeneo/Dockerfiles#340]
Conditions for PHP_XDEBUG_ENABLED can be simplified in entrypoint.sh files.

**Comment by lars85** [comment]
https://www.shellcheck.net/ says
```
Line 35:
if [ ! -z "${PHP_XDEBUG_ENABLED}" ]; then
     ^-- SC2236: Use -n instead of ! -z.
```
in old version (current master).

My patch would also solve this problem.

**Comment by damien-carcel** [comment]
Hey Lars.

Thank you so much for this contribution. I merged your PR, the Docker Hub is currently building the new images. I'll close this issue when the build is complete (should be by the end of the morning).

Cheers,
Damien.
