### ISSUE TITLE
Problem with eval in entrypoint.sh in GitLab CI 

### ISSUE THREAD

**Issue by lars85** [akeneo/Dockerfiles#342]
Using the `akeneo/fpm:php-7.*` docker images in `.gitlab-ci.yml` causes this error in pipeline:
```
Skipping Git submodules setup
/usr/local/bin/entrypoint.sh: eval: line 41: syntax error near unexpected token `then'
/usr/local/bin/entrypoint.sh: eval: line 41: syntax error near unexpected token `then'
ERROR: Job failed: exit code 2
```

I've found the solution in this Gitlab-Runner issue:
https://gitlab.com/gitlab-org/gitlab-runner/issues/1253

**Comment by damien-carcel** [comment]
Hi @lars85.

Thanks for this new bug fix :slightly_smiling_face:. Your PR is merged, I'll close this issue once the Docker Hub finished building the images. As always, it will take a few hours.

Cheers,
Damien.
