### ISSUE TITLE
Missing required extensions when using Akeneo PIM enterprise

### ISSUE THREAD

**Issue by amansilla** [akeneo/Dockerfiles#348]
| Q                      | A
| ---------------------- | -----
| Bug report?            | yes/no
| Feature request?       | yes/no
| BC Break report?       | yes/no
| RFC?                   | yes/no
| Affected image and tag | akeneo/image:tag

The PHP extensions: `mcrypt` and `soap` are missing but required when executed the `pim:installer:check-requirements`.

**Comment by amansilla** [comment]
@damien-carcel I'm not sure how the solution looks like but probably you don't want to maintain different docker images for CE and EE .

**Comment by damien-carcel** [comment]
Hi @amansilla. This is strange. What version of the PIM are you using?

Those images are used on the CI for both PIM EE and CE. There should be no requirements issue, except with the master branches of the PIM, but `master` now use its own Dockerfile, directly present in the PIM GitHub repository.

**Comment by amansilla** [comment]
That's really weird. I've removed all images and container from my host and executing ```docker run akeneo/fpm:php-7.2 php -v``` get the following output:

```bash
PHP 7.3.9-1+0~20190902.44+debian9~1.gbpf8534c (cli) (built: Sep  2 2019 13:31:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+0~20190902.44+debian9~1.gbpf8534c, Copyright (c) 1999-2018, by Zend Technologies
```
Is there any issue with the latest build of the image maybe?

**Comment by damien-carcel** [comment]
What the …?
Just tried it myself, on both `akeneo/php` and `akeneo/fpm` images, the PHP versions are fine.

I have no idea how you can end with such a result :open_mouth:.

**Comment by damien-carcel** [comment]
Oh, the images I just pulled are one month old...

**Comment by amansilla** [comment]
Yes really strange! After pulling again the image I got a new one where php version match. But in this case as you said the image is on month old. It's maybe a docker hub issue?

**Comment by damien-carcel** [comment]
OK. So, no, the images I just pulled are OK: they are 6 days old (last time they were generated by Travis CI, I just checked).
The version of PHP they contain is one month old => it is `7.3.8` for the 7.3 images, you had the `7.3.9`.

**Comment by damien-carcel** [comment]
So I really don't know what was the image you pulled, as it possessed a PHP version dated from Monday when the Akeneo images were built last Friday :open_mouth:

**Comment by amansilla** [comment]
You're right I misunderstood `built` information. I don't know what was the issue but probably docker + host specific related but since now it seems to work properly, I'll close the issue.

Thanks for your support, I hope you haven't loose much time investigating this.

Greetings! 😉
