### ISSUE TITLE
Fresh Akeneo in a production environment

### ISSUE THREAD

**Issue by dalarcia** [akeneo/Dockerfiles#349]
| Q                      | A
| ---------------------- | -----
| Bug report?            | no
| Feature request?       | no
| BC Break report?       | no
| RFC?                   | no
| Affected image and tag |

HI group. This is my first post so I hope I'm writing it in the right place :-)

I'm new with Akeneo PIM and after reading Akeneo doc and installing it with Docker and also akeneo images in some test environment, I would like to know how to do a fresh install in a production environment.

I have read that in a production environment **it is not recommended the use of the Akeneo Docker images**, so my questions are:

- How I must do a fresh install of Akeneo in a production environment?
- Is it the best way to do it with Docker? -> https://docs.akeneo.com/3.0/install_pim/docker/installation_docker.html And if so, What images should I use to do it?
- Is it the best way to do it manually? -> https://docs.akeneo.com/3.0/install_pim/manual/index.html

Thanks in advance.

**Comment by damien-carcel** [comment]
Hello @dalarcia.

Indeed, these Docker images are not recommended for production. They would work, but just contains stuff that shouldn't be present in a production environment, like XDebug or Composer.

My recommendation: if your production environment is a dedicated server, then just install on it what is needed to make the PIM run by following the manual install documentation you linked above.

Docker is usable in production, but it is a lot more complex to put correctly in place and must be done only if you really master it: meaning automated build of Docker images containing the PIM, correct setup of the Database images to have data in external Docker volumes with automatic backups, … Sadly we have no documentation for such a setup.

**Comment by dalarcia** [comment]
Thank you very much @damien-carcel. I will follow your suggestion. 

Best regard.
